config/routes.rb
Rails.application.routes.draw do
  # set the controller and action to go to upon visiting '/'
  # the format is: root 'controller#action'
  root 'cities#index'

  resources :cities, only: :index do
    resources :parks, except: :destroy do
      resources :reviews, except: [:index, :show]
    end
  end
  
  # for custom routes, the format is get 'yourpathhere', to: "controller#action"
  get '/cities/all', to: "cities#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :parks
end

app/models/park.rb
class Park < ApplicationRecord
  belongs_to :city
  has_many :reviews

  validates :name, :description, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :park

  validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @city = City.find(params[:city_id])
    @parks = @city.parks
  end

  def show
    @city = City.find(params[:city_id])
    @park = Park.find(params[:id])
  end

  def new
    @city = City.find(params[:city_id])
    @park = Park.new
  end

  def edit
    @city = City.find(params[:city_id])
    @park = Park.find(params[:id])
  end

  def create
    @city = City.find(params[:city_id])
    @park = Park.new(park_params)
    @park.city = @city

    if @park.save
      # redirect to the park show
      redirect_to city_park_path(@city, @park)
    else
      @errors = @park.errors.full_messages
      # render the new page again
      # for argument to render, look inside view folder, not routes!
      render 'new'
    end
  end

  def update
    @city = City.find(params[:city_id])
    @park = Park.find(params[:id])
    if @park.update(park_params)
      # redirect to the park show
      redirect_to city_park_path(@city, @park)
    else
      @errors = @park.errors.full_messages
      # render the edit page again
      render 'edit'
    end
  end

  private

  def park_params
    params.require(:park).permit(:name, :description, :city)
  end

  # being dry

  def set_city_and_park
    @city = City.find(params[:city_id])
    @park = Park.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_city_and_park

  def new
    @review = Review.new

    if request.xhr?
      render partial: 'form'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @review.park = @park

    if @review.save
      if request.xhr?
        render json: @review
      else
        redirect_to city_park_path(@city, @park)
      end
    else
      @errors = @review.errors.full_messages
      render 'new'
    end
  end

  def update
    if @review.update(review_params)
      redirect_to city_park_path(@city, @park)
    else
      @errors = @review.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to city_park_path(@city, @park)
  end

  private

  def review_params
    params.require(:review).permit(:title, :body, :park)
  end

  def set_city_and_park
    @city = City.find(params[:city_id])
    @park = Park.find(params[:park_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cities/index.html.erb
<p class="bg-info">
  Find me in app/views/cities/index.html.erb
</p>

<% @cities.each do |city| %>
  <p>
    <!-- Want these all to be links to the city show for each city -->
    <!-- link_to DISPLAY_TEXT, PATH, OPTIONAL_ARGUMENTS(e.g. ID, remote: true, etc.) -->

    <!-- note: if you'd like to style the HTML object that is created by the Rails helper by giving it a class or an ID, you must do that directly and not to a parent element. -Ellie -->
    <%= link_to city.name, city_parks_path(city) %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkrAnon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parks/edit.html.erb
<p class="bg-info">
  Find me in app/views/parks/edit.html.erb
</p>

<h3>
  Edit a new park listing
</h3>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>

<div>
<!-- Want a form that routes to the correct path here to update a park -->
<%= form_for [@city, @park] do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>
</div>

app/views/parks/index.html.erb
<p class="bg-info">
  Find me in app/views/parks/index.html.erb
</p>

<h3>
  All Parks for <%= @city.name %>
</h3>

<p>
  <!-- Want this to be a link to the create a new park page -->
  <%= link_to 'Create a new park', new_city_park_path(@city) %>
</p>

<p>
  <% @parks.each do |park| %>
    <p>
      <!-- Want these all to be links to the parks show for each park -->
      <%= link_to park.name, city_park_path(@city, park), class: "parkling" %>
    </p>
  <% end %>
</p>

app/views/parks/new.html.erb
<p class="bg-info">
  Find me in app/views/parks/new.html.erb
</p>

<h3>
  Create a new park listing
</h3>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>

<div>
  <!-- Want a form that routes to the correct path here to create a park -->

  <!-- caution: form_for is not the same as form_tag -->
  <!-- form_for takes active record object(s) and form_tag takes a path -->
  <!-- thanks michael and ellie :D -->
<%= form_for [@city, @park] do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name, placeholder: "Enter park name", value: @park.name %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description, placeholder: "Describe the park", value: @park.description %><br>

  <%= f.submit %>
<% end %>
</div>

app/views/parks/show.html.erb
<p class="bg-info">
  Find me in app/views/parks/show.html.erb
</p>

<h3>
  Information for <%= @park.name %>
</h3>

<p>
  <!-- Want this city name to be a link back to the city -->
  <strong>City:</strong> <%= link_to @city.name, city_parks_path(@city) %><br>
  <strong>Description:</strong> <%= @park.description %>
</p>

<p>
  <!-- Want this to be a link to edit the park information -->
  <%= link_to 'Edit Park Information', edit_city_park_path(@city, @park)  %></span>
</p>

<h4>
  Reviews for <%= @park.name %>
</h4>

<p>
  <!-- Want this to be a link to the create a new review page -->
  <!-- remote: true tells Rails that upon clicking this link (or in the case of a form, submitting the form), you are making an xhr request -->
  <%= link_to 'Create a new review', new_city_park_review_path(@city, @park), class: 'new_review_link', remote: true %>

  <div id="form-container">
  </div>
</p>

<p>
  <% @park.reviews.each do |review| %>
    <p>
      <strong>Title:</strong> <%= review.title %><br>
      <strong>Body:</strong> <%= review.body %><br>
      <!-- Want this to be a link to edit the review -->
      <span class='small text-danger'>Edit Review</span><br>
      <!-- Want this to be a link to delete the review -->
      <span class='small text-danger'>Delete Review</span>
    </p>
  <% end %>
</p>

app/views/reviews/_form.html.erb
<%= form_for [@city, @park, @review], remote: true do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title, placeholder: "Title of your Review" %><br>

  <%= f.label :body %><br>
  <%= f.text_area :body, placeholder: "Describe your experience at the park" %><br>

  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<p class="bg-info">
  Find me in app/views/reviews/edit.html.erb
</p>

<h3>
  Create a new review for <%= @park.name %>
</h3>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>

<div>
  <%= form_for([@city, @park, @review]) do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Title of your Review" %><br>

    <%= f.label :body %><br>
    <%= f.text_area :body, placeholder: "Describe your experience at the park" %><br>

    <%= f.submit %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<p class="bg-info">
  Find me in app/views/reviews/new.html.erb
</p>

<h3>
  Create a new review for <%= @park.name %>
</h3>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>

<div>
  <%= form_for([@city, @park, @review], remote: true) do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Title of your Review" %><br>

    <%= f.label :body %><br>
    <%= f.text_area :body, placeholder: "Describe your experience at the park" %><br>

    <%= f.submit %>
  <% end %>
</div>